### ISSUE TITLE
Add GeoLocation field to profile

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#108]
Add Optional Geolocation tag to profile. 

People can choose to reveal their location or not. 

Also, some Tasks might be needed to be done in a specific geo location. Add Geolocation to tasks as well.

**Comment by f-gate** [comment]
I am removing the balance field from profile as its duplication and will not be updated by the balances pallet.

**Comment by stojanov-igor** [comment]
How do we check the balance for a profile then? We have to document this because it breaks the UI.

**Comment by f-gate** [comment]
https://stackoverflow.com/questions/64210673/how-do-you-format-balances-with-the-polkadot-js-api
