### ISSUE TITLE
Fix transfer function in Task Pallet

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#22]
Within the Task pallet, we have a [transfer_balance](https://github.com/UniversalDot/pallets/blob/master/task/src/lib.rs#L410) function which should send funds from one balance to another. This function internally makes a call to `Currency::transfer`. 

- [x] Investigate why the transfer function is not working in the current implementation.
- [x] Implement a fix.
- [x] Create unit tests to properly test the function.

Budget for this task: $25.

**Comment by vivekvpandya** [comment]
I think the issue is that error case of `Currency::transfer()` is not used and even if there are some error in `Currency::transfer()` the `transfer_balance()` will return `Ok(())`
```
  15         // Function to transfer balance from one account to another                                                                                                                                   
   14         #[transactional]                                                                                                                                                                              
   13         pub fn transfer_balance(task_initiator: &T::AccountId, task_volunteer: &T::AccountId, budget: BalanceOf<T>) -> Result<(), Error<T>> {                                                         
   12             // TODO: Investigate why Currency transfer doesn't work                                                                                                                                   
   11             // TODO: See proper testing https://docs.substrate.io/how-to-guides/v3/testing/transfer-function/                                                                                         
   10                                                                                                                                                                                                       
    9             //let task_initiator = task.initiator.clone();                                                                                                                                            
    8             log::info!("budget {:?}.", budget);                                                                                                                                                       
    7             log::info!("signer {:?}.", task_initiator);                                                                                                                                               
    6             log::info!("task_volunteer {:?}.", task_volunteer);                                                                                                                                       
    5             ensure!(<T as self::Config>::Currency::free_balance(task_initiator) >= budget, <Error<T>>::NotEnoughBalance);                                                                             
    4             let result = <T as self::Config>::Currency::transfer(task_initiator, task_volunteer, budget, ExistenceRequirement::KeepAlive);                                                            
    3             log::info!("Result Output {:?}.", result);                                                                                                                                                
    2                                                                                                                                                                                                       
    1             Ok(())                                                                                                                                                                                    
  423         }  
```
IMHO pallet should not return `Error<T>` instead use `DispatchError`. If we do that refactoring to task pallet then error from `Currency::transfer()` can be propagated to caller of `transfer_balance()` by just using `?` with `Currency::transfer()` call. 
I don't see any specific reason for not using `DispatchError` as return type in pallets.
For example check https://github.com/substrate-developer-hub/pallet-did/blob/8510c92b4e550caded56aa7809046066db0f1590/src/lib.rs#L546

**Comment by vivekvpandya** [comment]
Also in the current simple test for transfer I see no balances is minted before making a transfer so it is expect to fail.

**Comment by stojanov-igor** [comment]
I think your investigation is right... 

Can you create a feature branch from : [universal-develop](https://github.com/UniversalDot/pallets/commits/universal-develop) and implement the fix together with a test. 

You can make a pull requesting to merge back into universal-develop again. 

Nice work so far.

**Comment by vivekvpandya** [comment]
I also see that in pallets there are certain functions used like `unwrap()` , `expect()` which should not be used as if pallets gets a panic it will halt block production and that is really bad thing for a polkadot para-chain. All pallet operation must either successful or return proper Error thorough DispatchError and Runtime will not break due to panic.

**Comment by stojanov-igor** [comment]
Verified! 

Transfer works! 

Marking this completed
