### ISSUE TITLE
Implement deadline functionality for Task

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#23]
In the [Task Pallet](https://github.com/UniversalDot/pallets/blob/master/task/src/lib.rs#L106), we have a `deadline` property that is currently not implemented. 

The deadline is the number of expected blocks until which the task is expected to be completed. For example: if the user inputs `1000` we expect that the task becomes obsolete and is removed 1000 blocks from the date of submission. 

This feature requires: 

- [ ] Implement functionality that removes a task after the deadline has passed. 
- [ ] Add unit tests
- [ ] Come up with a design that translates date/time attributes into block time (*See note)

The React application should eventually allow date/time input into the application. For example, The user can select Wednesday 12.00pm as the deadline. This needs to be translated into block time into the pallet.

Task Budget: $40.

**Comment by vivekvpandya** [comment]
I think we have two options here.
1) On chain: in `on_initialize()` hook check for all task id their deadline has passed then remove them. This can be a costly operation to be performed , so we may add a time duration parameter only after that time interval passed we do the processing.
2) Have an off-chain worker do the above job and submit extrinsic to remove the task.

To start with I will implement option 1).

**Comment by vivekvpandya** [comment]
>The React application should eventually allow date/time input into the application. For example, The user can select Wednesday 12.00pm as the deadline. This needs to be translated into block time into the pallet.

I think for this we can have following design 

1.  User creates task with a time from front-end (node receives UnixTime stamp) if time is already passed then creation errors, otherwise task is created.
2. node uses Timestamp pallet and check based on above option to compare if current_time stamp is over the deadline then remove the task.

**Comment by stojanov-igor** [comment]
> I think we have two options here.
> 
> 1. On chain: in `on_initialize()` hook check for all task id their deadline has passed then remove them. This can be a costly operation to be performed , so we may add a time duration parameter only after that time interval passed we do the processing.
> 2. Have an off-chain worker do the above job and submit extrinsic to remove the task.
> 
> To start with I will implement option 1).

I think on_initilize is a better solution for now. At every new_block we have to check tasks with an expired deadline and remove them from storage.  Be careful with the logic that you inject on_initialize because if errors are not properly handled, might risk bricking the blockchain. 





> > The React application should eventually allow date/time input into the application. For example, The user can select Wednesday 12.00pm as the deadline. This needs to be translated into block time into the pallet.
> 
> I think for this we can have following design
> 
> 1. User creates task with a time from front-end (node receives UnixTime stamp) if time is already passed then creation errors, otherwise task is created.
> 2. node uses Timestamp pallet and check based on above option to compare if current_time stamp is over the deadline then remove the task.

The node shall receive UnixTime, but we have to convert the current local time into UnixTime. I think that conversion should happen in the front-end, and be sent to the node. We can do front-end validation to make sure the user inputs correct dates, but having some logic that checks for errors in the node would be useful too. 
Check out this: https://stackoverflow.com/questions/68262293/substrate-frame-v2-how-to-use-pallet-timestamp .

**Comment by stojanov-igor** [comment]
This issue is resolved in https://github.com/UniversalDot/universal-dot-node/pull/28
