### ISSUE TITLE
Add additional characteristics to Profile

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#34]
The Profile **Struct** should be enriched with additional properties. The additional characteristics list is shown below. 

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-09ce6001-7fff-7b0b-17a7-f757f4e9e310"><div dir="ltr" style="margin-left:0pt;" align="left">

Characteristic | Description | Type | Entry
-- | -- | -- | --
AccountID | Primary ID for a profile. One profile per AccountID | Pub key | Automatic
Portfolio | User can showcase personal portfolio, additional description, etc | String (may contain list of IPFS documents) | Manual, Optional
Availability | Hours per week the User is Available | Number (approx. Or list of 10hr,20hr,30hr) | Manual, Mandatory
Profile History | Previous work history of the User | Array of Tasks | Automatic

</div></b>
When the is automatic entry, populate these fields automatically. For example, Collect all the tasks that the user has completed into an array of Tasks.

- [ ] Implement additional properties
- [ ] Revise and add tests appropriately

Budget: $50

**Comment by stojanov-igor** [comment]
I have already created a branch for you...

```
git fetch origin
git checkout 34-add-additional-characteristics-to-profile
```

**Comment by vivekvpandya** [comment]
I see  AccountID is only way to uniquely identify Profile.
```
    2     #[pallet::storage]                                                                                         
    1     #[pallet::getter(fn profiles)]                                                                             
  111     /// Stores a Profile unique properties in a StorageMap.    Joseph Knecht, 05/04/22 17:50 • import pallets a
    1     pub(super) type Profiles<T: Config> = StorageMap<_, Twox64Concat, T::AccountId, Profile<T>>;
```
So first row in above table is already covered. Unless I have miss understood something.

**Comment by stojanov-igor** [comment]
> I see AccountID is only way to uniquely identify Profile.
> 
> ```
>     2     #[pallet::storage]                                                                                         
>     1     #[pallet::getter(fn profiles)]                                                                             
>   111     /// Stores a Profile unique properties in a StorageMap.    Joseph Knecht, 05/04/22 17:50 • import pallets a
>     1     pub(super) type Profiles<T: Config> = StorageMap<_, Twox64Concat, T::AccountId, Profile<T>>;
> ```
> 
> So first row in above table is already covered. Unless I have miss understood something.

Great. So we only have to add 3 additional properties.

**Comment by vivekvpandya** [comment]
Question For Task History of given account, In task pallet I see that we have bound on T::MaxTasksOwned. But I think we can't have similar bound on how many task a user can complete. 
Also is this data really consensus critical? if not we can just use https://subsquid.io/ where we can observe events of TaskCompletion otherwise we can store it on separate DB which is not under consensus.

**Comment by stojanov-igor** [comment]
For now, we should not have a limit on the number of tasks a user can complete. 
Maybe we can introduce it later if needed.
Showing which tasks a user has completed might need a limit, but we will manage that from the front end.

**Comment by vivekvpandya** [comment]
Repeating tasks from storage of Task pallet to Profile pallet seems unnecessary extra work. 
Frontend can read the task's storage and filter based on "volunteer" who finished the task.
Or best is to use subsquid like solution to digest task_accepted event and then make GraphQL query for volunteer == user to find completed tasks by given user.

**Comment by stojanov-igor** [comment]
> Repeating tasks from storage of Task pallet to Profile pallet seems unnecessary extra work. Frontend can read the task's storage and filter based on "volunteer" who finished the task. Or best is to use subsquid like solution to digest task_accepted event and then make GraphQL query for volunteer == user to find completed tasks by given user.

The front-end to do a search through all tasks based on volunteer is a heavy computation. Instead, we can add Task ID to the Profile History Vector to blockchain storage. Maybe we can set a limit on the number of tasks (ex. last 70) that are added to Profile History? 

Storing the tasks off-chain might be a good solution at a later time...
