### ISSUE TITLE
Escrow funds when task is Started

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#40]
Currently, a Balance transfer is made when the task has been completed. This can be further enhanced with escrow functionality.

When task is _Created_, the budget funds are locked in escrow. Funds are released and transferred when the task is _Accepted_.

To make sure that the user can't double spend these funds, we have to lock the Task Balance amount into an escrow account. 

Funds are to be released when the task has been accepted. 

- [x] Implement escrow functionality for transferring funds.
- [x] Unit tests.

Budget: $50

**Comment by vivekvpandya** [comment]
A single escrow account for task pallet should be sufficient for all task right? @JosephKnecht-lab do you see any issues with that?

**Comment by vivekvpandya** [comment]
@JosephKnecht-lab I have found one issue with how task pallet handles deadline passed tasked.
In on_initialize() hook we just delete those tasks and volunteer gets fund from task_initiator(without completing work!) , which seems incorrect.
