### ISSUE TITLE
Expired Tasks

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#46]
Store **expired** tasks in a list to be deleted or edited by task creator for a certain amount of blocks (1 or 2 weeks). 

After 2 weeks, tasks are permanently deleted.

**Comment by f-gate** [comment]
https://github.com/UniversalDot/universal-dot-node/issues/65

**Comment by f-gate** [comment]
When a task is updated, the hash of the task changes and the old hash is pushed to storage. i find this strange and will have to discuss.
