### ISSUE TITLE
Add DAO property to Task

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#53]
Currently, in the DAO pallet we have a collection of tasks that belong to a certain DAO. The task is agnostic to which organization it belongs. This design can be improved by adding an additional property to the TASK struct where we can state the organization to which the task belongs. 

The task may not belong to any organization, so it is an optional field.

- [x] Refactor code to add Dao property to task
- [x] Add Tests
- [x] Remove unnecessary functionality in DAO pallet where tasks are added to DAO
- [x] Verify DAO identifier (via loose coupling) during task creation/updates

**Comment by evilrobot-01** [comment]
@JosephKnecht-lab  

Do you mean adding an optional property to the [Task](https://github.com/UniversalDot/universal-dot-node/blob/5d29702f3e4466b53ce2d4659654e79fdce73aa8/pallets/task/src/lib.rs#L136-L154) struct within the `Task` pallet?

Also, would you prefer `Dao` or `Organization`? The latter is perhaps more general so might be a better name for future-proofing.

**Comment by stojanov-igor** [comment]
> Do you mean adding an optional property to the [Task](https://github.com/UniversalDot/universal-dot-node/blob/5d29702f3e4466b53ce2d4659654e79fdce73aa8/pallets/task/src/lib.rs#L136-L154) struct within the `Task` pallet?

Yes. 

Lets keep it DAO for now.

**Comment by evilrobot-01** [comment]
@JosephKnecht-lab 

Do you want to verify that an organization/dao exists with supplied identifier when creating/updating the task? It will require a lookup via the Dao pallet, so would need to loosely couple.

**Comment by stojanov-igor** [comment]
It would be useful to have the check.

@evilrobot-01 What do you think?

**Comment by evilrobot-01** [comment]
Completed other items, so will add as a task to this issue.
