### ISSUE TITLE
Grant Pallet

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#55]
Faucet Pallet 

We are planning to airdrop tokens to the community once we launch the testnet. For this reason we need a new Faucet Pallet which has the following features:

- [x] Allow funds to be sent to Treasury account
- [x] transfer funds to requester parties
- [x] One grant reward per block
- [x] Implement tests for pallet functionality
- [x] benchmark
- [x] Pays no fees on request

Budget: $60

**Comment by f-gate** [comment]
Current implementation: 

One account wins per block,
Balance of account must be zero,

There is nothing currently in place to prevent sybil attacks.

**Comment by stojanov-igor** [comment]
Just as we discussed, the extrinsic to request funds should pay no fees.

**Comment by f-gate** [comment]
I still think we need some way of combatting sybil attacks.

I believe with pays no fees we are letting people freely congest the system....
a primitive solution may be to only allow requests if they are not on the requestor list however, this still doesnt get around having multiple addresses.

For this we may need to use some kind of referral system, reputation or deposit of sorts?

**Comment by stojanov-igor** [comment]
Game theory, am I right?

The grant amount won't be too large, so it should discourage people from gaming the system. Also, once we get traction with the application, we can reduce this grant amount or remove it all-together.
