### ISSUE TITLE
Update escrow to use ReservableCurrency

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#59]
Within the task pallet, we use an escrow account in order to lock up funds when a task is created. The escrow account then transfers the balance to the volunteer who completed the task. 

Refactor this functionality to see if we can use ReservableCurrency instead. 

- [x] Refactor the escrow account out and use Reservable Currency
- [x] Implement tests

https://docs.rs/frame-support/3.0.0/frame_support/traits/trait.ReservableCurrency.html

**Comment by f-gate** [comment]
Refactor: 
- [x] create_task + test
- [x] update_task + test
- [x] accept_task  + test
- [x] delete_task + test

**Comment by f-gate** [comment]
Going to write some more tests i can think of.

**Comment by f-gate** [comment]
There is a possibility on unreserve() to reap the account if it is less than the existential deposit, perhaps need discussion

https://paritytech.github.io/substrate/master/frame_support/traits/trait.ReservableCurrency.html
