### ISSUE TITLE
Update pallet version from NOV 2021 to latest

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#60]
All pallets and runtime Cargo versions are tagged with `tag = 'monthly-2021-11'`. 

We would need to update to the latest versions.

**Comment by evilrobot-01** [comment]
Do you want to standardise on the latest as of now (monthly-2022-08)? It seems that those are pre-release tags. Full list at https://github.com/paritytech/substrate/tags

PS - any data migrations to worry about?

**Comment by stojanov-igor** [comment]
We should use the latest. What is their recommended approach? 

We don't have to migrate any data since we are only running a testnet.

**Comment by evilrobot-01** [comment]
Will see if I can find an official recommendation but if not, will go with latest.

What about Rust edition? Their latest codebase seems to be on 2021 whereas this is still on 2018 - want that updated at the same time?

**Comment by stojanov-igor** [comment]
> What about Rust edition? Their latest codebase seems to be on 2021 whereas this is still on 2018 - want that updated at the same time?
Yes. But one thing at a time.  You don't want to break everything at once.

**Comment by evilrobot-01** [comment]
As per https://substrate.stackexchange.com/questions/2812/is-substrate-actively-published-on-crates-io, it seems that the `monthly` releases are automated snapshots whereas the `polkadot` releases are properly versioned, so more stable.

Do you want to start tracking `polkadot` rather than `monthly` as you are nearing `1.0`, or would you still prefer more regular updates?

**Comment by stojanov-igor** [comment]
yea. we can start tracking polkadot. 

Let me know if you encounter any issues with the upgrade..

**Comment by stojanov-igor** [comment]
@evilrobot-01  This was completed and already merged into universal-develop as part of another user story. 

Closing it for now...
