### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#67]
- [x] `#[pallet::unbounded]` used on all storage items which used unbounded vectors. This was to reduce the complexity of the update to latest and another issue should be created to tackle.
- [X] Used `bounded_*()` helper functions for Dao tests, but only as a wrapper until the pallet can be fully migrated to bounded vecs.
- [x] assess public visibility of helper functions in `dao` pallet
- [x] ensure that usage of `into_account_truncating()` is correct within `task` pallet
- [x] set max lengths of new config items of `dao` config in runtime. These are used by the Dao struct and were previously unbounded.
- [x] there were upstream changes to RPC apis (`jsonrpsee`) , need to check that all still works from the front-end. 
- [ x review possible switch to new `list_benchmarks!` and `add_benchmarks!` macros within runtime benchmarks
- [x] Cargo.lock should not be included within source control for library crates (pallets) : [source](https://github.com/rust-lang/cargo/issues/315#issuecomment-634598379)

**Comment by evilrobot-01** [comment]
@JosephKnecht-lab shall I create separate issues/PRs for the above outstanding tasks (where appropriate) to make merging easier. or just keep it all together under a single issue/branch?

**Comment by stojanov-igor** [comment]
Creating separate tasks/branch sounds like too much overhead. 

We can keep it all in one branch.
