### ISSUE TITLE
Fixes to Release 0.7

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#69]
- [x] When creating a new organization, the old organization is deleted. Create a test to verify that the founder can create multiple organizations. Also, verify that MemberOf can hold more than one organization. 
- [x] Vision in organization needs to consider with existing vision document. This is to be resolved with https://github.com/UniversalDot/universal-dot-node/issues/68
- [x] After tasks has been accepted and removed from storage, it should be cleared from the DAO task list as well.

**Comment by f-gate** [comment]
https://github.com/UniversalDot/universal-dot-node/pull/82

**Comment by f-gate** [comment]
Branch 69 has not been merged.
