### ISSUE TITLE
Sudo Pallet

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#73]
The application requires a sudo account that will have privileged access. This sudo account will be used for unforeseen protocol changes that might have to be made. 

The sudo account is to be dropped after max 1 year and the system is to be governed solely through democracy.

https://crates.io/crates/pallet-sudo

**Comment by evilrobot-01** [comment]
`pallet-sudo` is already implemented with the sudo key being set to Alice in the chain spec config (`testnet_genesis`). This would need setting to a proper key before testnet going live.
